@REM SET DIRCMD=/A /P /O
SET PATH=C:\DEVEL\I16GNU\BIN;C:\DJGPP\BIN;C:\LOCAL;C:\DEVEL\I16GNU\IA16-ELF\LIB
SET DJGPP=C:\DJGPP\DJGPP.ENV
SET TZ=:America/New_York
SET TMPDIR=C:\TMP

cd local
call compile.bat
@rem exit